services:

  # Database service for building and tests in pipeline
  database:
    image: ${NEO4J_IMAGE:-neo4j:5.9.0-enterprise}
    ports:
      - "${BIND_ADDRESS:-127.0.0.1}:${NEO4J_BOLT_PORT:-5087}:7687"
      - "${BIND_ADDRESS:-127.0.0.1}:${NEO4J_HTTP_PORT:-5074}:7474"
    environment:
      NEO4J_AUTH: "neo4j/changeme1234"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_trigger_enabled: "true"
      NEO4J_server_memory_heap_initial__size: "2G"
      NEO4J_server_memory_heap_max__size: "2G"
      NEO4J_server_memory_pagecache_size: "1G"
      NEO4J_server_default__listen__address: "0.0.0.0"
      NEO4J_server_default__advertised__address: "localhost"
      NEO4J_metrics_jmx_enabled: "true"
      NEO4J_PLUGINS: '["apoc"]'
    healthcheck:
      test: wget --quiet --spider --timeout 2 --tries 1 "http://localhost:7474/" || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 60s

  # Clinical-MDR API service for running tests in pipeline
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_IMAGE: ${PYTHON_IMAGE:-python:3.11.3-slim}
        TARGET: ${BUILD_TARGET:-dev}
        UID: ${UID:-1000}
    environment:
      NEO4J_DSN: "${NEO4J_DSN:-bolt://neo4j:changeme1234@database:7687}/neo4j"
      ALLOW_ORIGIN_REGEX: "${ALLOW_ORIGIN_REGEX:-.*}"
      OAUTH_ENABLED: "${OAUTH_ENABLED:-False}"
      OAUTH_RBAC_ENABLED: "${OAUTH_RBAC_ENABLED:-False}"
      OIDC_METADATA_DOCUMENT: "${OIDC_METADATA_DOCUMENT}"
      OAUTH_APP_ID: "${OAUTH_APP_ID}"
      OAUTH_APP_SECRET: "${OAUTH_APP_SECRET}"
      MS_GRAPH_INTEGRATION_ENABLED: "${MS_GRAPH_INTEGRATION_ENABLED}"
      MS_GRAPH_GROUPS_QUERY: "${MS_GRAPH_GROUPS_QUERY}"
    ports:
      - "${BIND_ADDRESS:-127.0.0.1}:${MDR_API_PORT:-8000}:8000"
