services:

  # Database service for building and tests in pipeline
  database:
    image: ${NEO4J_IMAGE:-neo4j:4.4.12-enterprise}
    ports:
      - "${BIND_ADDRESS:-127.0.0.1}:${NEO4J_BOLT_PORT:-5087}:7687"
      - "${BIND_ADDRESS:-127.0.0.1}:${NEO4J_HTTP_PORT:-5074}:7474"
    environment:
      NEO4J_AUTH: "neo4j/changeme1234"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_trigger_enabled: "true"
      NEO4J_dbms_memory_heap_initial__size: "2G"
      NEO4J_dbms_memory_heap_max__size: "2G"
      NEO4J_dbms_memory_pagecache_size: "1G"
      NEO4J_dbms_default__listen__address: "0.0.0.0"
      NEO4J_dbms_default__advertised__address: "localhost"
      NEO4J_metrics_jmx_enabled: "true"
      NEO4JLABS_PLUGINS: '["apoc"]'
    healthcheck:
      test: wget --quiet --spider --timeout 2 --tries 1 "http://localhost:7474/" || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 60s

  # Clinical-MDR API service for running tests in pipeline
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_IMAGE: ${PYTHON_IMAGE:-python:3.11.3-slim}
        TARGET: ${BUILD_TARGET:-dev}
        UID: ${UID:-1000}
    environment:
      NEO4J_DSN: "bolt://${NEO4J_MDR_AUTH_USER:-neo4j}:${NEO4J_MDR_AUTH_PASSWORD:-changeme1234}@${NEO4J_MDR_DATABASE:-database}:7687"
      NEO4J_DATABASE: "${NEO4J_DATABASE:-neo4j}"
      OAUTH_ENABLED: "False"
      ALLOW_ORIGIN_REGEX: ".*"
    ports:
      - "${BIND_ADDRESS:-127.0.0.1}:${MDR_API_PORT:-8000}:8000"
